/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.miod.parser

import org.miod.parser.ast.*
import java.nio.file.Path
import kotlin.test.*

class SyntaxParserTest {
    @Test fun undefinedIdentifierErrorClassTest() {
        val ce = UndefinedIdentifier(Location(
            Path.of("a", "sub"), TextPosition(1,1),
            TextPosition(2,5)
        ), "abc")
        assertEquals("error: a/sub: (1:1)..(2:5): abc is undefined", ce.toString())
    }

    @Test fun unitHeaderTest() {
        println(System.getProperty("user.dir"))
        val builder = AstBuilder(Path.of("test-sources", "empty_unit.miod"))
        val parserResult = builder.parse()
        println(builder.errors.errors)
        assertTrue(parserResult)
        val astResult = builder.buildAst()
        assertTrue(astResult)
    }

    @Test fun unitHeaderWithAnnotationsAndCommentsTest() {
        val builder = AstBuilder(Path.of("test-sources", "empty_unit_body.miod"))
        val result = builder.parse()
        println(builder.errors.errors)
        assertTrue(result)
        assertTrue(builder.buildAst())
    }

    @Test fun constWithAnnotationTest() {
        val builder = AstBuilder(Path.of("test-sources", "const_with_annotation.miod"))
        val result = builder.parse()
        println(builder.errors.errors)
        assertTrue(result)
        assertTrue(builder.buildAst())
    }

    @Test fun unitRedeclarationTest() {
        val builder = AstBuilder(Path.of("test-sources", "unit_redecl.miod"))
        val parseResult = builder.parse()
        println(builder.errors.errors)
        assertTrue(parseResult)
        assertFalse(builder.buildAst())
        println(builder.errors.errors)
        assertIs<UnitRedeclaration>(builder.errors.errors[0])
        assertIs<UnitRedeclaration>(builder.errors.errors[1])
    }

    @Test fun allConstructsTest() {
        val builder = AstBuilder(Path.of("test-sources", "all_constructs.miod"))
        val parseResult = builder.parse()
        println(builder.errors.errors)
        assertTrue(parseResult)
        assertTrue(builder.buildAst())
        println(builder.errors.errors)
    }
}
